#!/bin/sh

PACKAGE_ROOT=${IPKG_INSTROOT:-}
CONFIG_DIR="$PACKAGE_ROOT/etc/mihomo"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
CONFIG_EXAMPLE="$PACKAGE_ROOT/usr/share/mihomo/config.yaml.example"

mkdir -p "$CONFIG_DIR"
if [ ! -e "$CONFIG_FILE" ]; then
	cp "$CONFIG_EXAMPLE" "$CONFIG_FILE"
	chmod 0600 "$CONFIG_FILE"
fi

exit 0
